pipeline {
    agent any

    environment {
        imageVersion = ""
        infrastructureStackName = "epam-phase3-stack"
        stackName = "petclinic-service-stack"
        serviceTemplate = "services/petclinic-service/service.yaml"
    }

    stages {

        stage('Cloning Git repo') {
          steps {
              sshagent (credentials: ['464b0ae2-8c8a-4c41-9b8e-c34b1f5e76c5']) {
                        git branch: 'master', url: 'git@github.com:RomanOrlovskiy/aws-cfn-petclinic.git', credentialsId: '464b0ae2-8c8a-4c41-9b8e-c34b1f5e76c5'
                }
          }
        }

        stage ('Change app version') {
            steps {
                script {
                    //parse selected git tag to remove the initial character 'v'
                    imageVersion = params.TAG[0] != "v" ? params.TAG : params.TAG.substring(1, params.TAG.length())
                }
                //sh "aws cloudformation update-stack --stack-name ${infrastructureStackName} --use-previous-template --parameters ParameterKey=ImageVersion,ParameterValue=${imageVersion}"
                println "Deploying the stack ${stackName}..."
                sh "aws cloudformation deploy --stack-name ${stackName} --template-file ${serviceTemplate} --capabilities CAPABILITY_NAMED_IAM --parameter-overrides ParameterKey=ImageVersion,ParameterValue=${imageVersion} ParameterKey=InfrastructureStackName, ParameterValue=${infrastructureStackName}"
            }
        }
    }
}
